name: build and deploy spring-api

on:
  push:
    branches: [ main, dev ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21
          cache: gradle

      - name: run tests
        run: ./gradlew clean test

      - name: build image with buildpacks
        run: ./gradlew bootBuildImage --imageName=${{ secrets.DOCKER_HUB_USERNAME }}/siges-api:latest

      - name: login docker
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: push image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/siges-api:latest
