spring.application.name=siges-api
server.servlet.context-path=/api

spring.jpa.hibernate.ddl-auto=validate

spring.docker.compose.file=compose.yaml,compose.dev.yaml
security.jwt.refresh.expiration=86400000
security.jwt.access.expiration=604800000