spring.flyway.out-of-order=true
# Database connection settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.docker.compose.enabled=false

logging.level.web=info
logging.level.dev=warn

app.recovery.web-success-url=${PASSWORD_RECOVERY_WEB_SUCCESS_URL}
app.recovery.web-used-url=${PASSWORD_RECOVERY_WEB_USED_URL}
app.recovery.web-expired-url=${PASSWORD_RECOVERY_WEB_EXPIRED_URL}
app.recovery.mobile-success-url=${PASSWORD_RECOVERY_MOBILE_SUCCESS_URL}
app.recovery.mobile-used-url=${PASSWORD_RECOVERY_MOBILE_USED_URL}
app.recovery.mobile-expired-url=${PASSWORD_RECOVERY_MOBILE_EXPIRED_URL}

aws.s3.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_S3_BUCKET}
aws.s3.cloudfront-domain=${AWS_CLOUDFRONT_DOMAIN}