spring.flyway.out-of-order=true
# Database connection settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.docker.compose.enabled=false

logging.level.web=info
logging.level.dev=info

app.recovery.mobile-redirect-url=${PASSWORD_RECOVERY_MOBILE_REDIRECT}
app.recovery.web-redirect-url=${PASSWORD_RECOVERY_WEB_REDIRECT}

aws.s3.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_S3_BUCKET}
aws.s3.cloudfront-domain=${AWS_CLOUDFRONT_DOMAIN}