spring.docker.compose.enabled=false
logging.level.dev=trace

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.orm.results=DEBUG
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.mail.username=test@test.com
spring.mail.password=fake

security.jwt.secret=test-secret


aws.s3.region=us-east-1
aws.s3.bucket-name=test-bucket
aws.s3.cloudfront-domain=cdn.test.local