spring.application.name=siges-api
server.servlet.context-path=/api

spring.jpa.hibernate.ddl-auto=validate

security.jwt.refresh_expiration=604800000
security.jwt.access_expiration=2764800000

login.max_attempts=3
login.lock_minutes=15

springdoc.show-actuator=true

app.recovery.mobile-redirect-url=${PASSWORD_RECOVERY_MOBILE_REDIRECT:https://frontend.com/reset-password}
app.recovery.web-redirect-url=${PASSWORD_RECOVERY_WEB_REDIRECT:myapp://reset-password}
app.recovery.token-expiration=PT15M

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health

management.health.group.readiness.incude: db, diskSpace

# AWS S3 Configuration
aws.s3.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET:test-bucket}
aws.s3.cloudfront-domain=${AWS_CLOUDFRONT_DOMAIN:domain.com}