spring.flyway.out-of-order=true
spring.datasource.url=jdbc:postgresql://localhost:5432/siges-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.docker.compose.file=compose.yaml,compose.dev.yaml

logging.level.org.springframework.security=trace
logging.level.dev=debug
logging.level.web=debug
security.jwt.secret=dev-secret