spring.application.name=siges-api
server.servlet.context-path=/api

spring.jpa.hibernate.ddl-auto=validate

security.jwt.refresh_expiration=86400000
security.jwt.access_expiration=604800000

springdoc.show-actuator=true