ALTER TABLE applicant_aud
    DROP CONSTRAINT fk_applicant_aud_on_idre;

ALTER TABLE equipments_aud
    DROP CONSTRAINT fk_equipments_aud_on_idre;

ALTER TABLE reservations
    DROP CONSTRAINT fk_reservations_on_petitioner;

ALTER TABLE spaces_aud
    DROP CONSTRAINT fk_spaces_aud_on_idre;

CREATE TABLE equipment_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(45)                             NOT NULL,
    description VARCHAR(400)                            NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_equipment_types PRIMARY KEY (id)
);

CREATE TABLE equipment_types_aud
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    id          BIGINT  NOT NULL,
    name        VARCHAR(45),
    description VARCHAR(400),
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_equipment_types_aud PRIMARY KEY (rev, id)
);

ALTER TABLE equipments
    ADD type_id BIGINT;

ALTER TABLE equipments_aud
    ADD type_id BIGINT;

ALTER TABLE equipment_types
    ADD CONSTRAINT uc_equipment_types_name UNIQUE (name);

ALTER TABLE applicant_aud
    ADD CONSTRAINT FK_APPLICANT_AUD_ON_IDRE FOREIGN KEY (id, rev) REFERENCES app_users_aud (id, rev);

ALTER TABLE equipments_aud
    ADD CONSTRAINT FK_EQUIPMENTS_AUD_ON_IDRE FOREIGN KEY (id, rev) REFERENCES reservables_aud (id, rev);

ALTER TABLE equipments
    ADD CONSTRAINT FK_EQUIPMENTS_ON_TYPE FOREIGN KEY (type_id) REFERENCES equipment_types (id);

ALTER TABLE equipment_types_aud
    ADD CONSTRAINT FK_EQUIPMENT_TYPES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_PETITIONER FOREIGN KEY (petitioner_id) REFERENCES applicant (id);

ALTER TABLE spaces_aud
    ADD CONSTRAINT FK_SPACES_AUD_ON_IDRE FOREIGN KEY (id, rev) REFERENCES reservables_aud (id, rev);