ALTER TABLE applicant_aud
    DROP CONSTRAINT fk_applicant_aud_on_idre;

ALTER TABLE equipments_aud
    DROP CONSTRAINT fk_equipments_aud_on_idre;

ALTER TABLE reservations
    DROP CONSTRAINT fk_reservations_on_petitioner;

ALTER TABLE spaces_aud
    DROP CONSTRAINT fk_spaces_aud_on_idre;

CREATE TABLE equipment_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(45)                             NOT NULL,
    description VARCHAR(400)                            NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_equipment_types PRIMARY KEY (id)
);

CREATE TABLE equipment_types_aud
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    id          BIGINT  NOT NULL,
    name        VARCHAR(45),
    description VARCHAR(400),
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_equipment_types_aud PRIMARY KEY (rev, id)
);

CREATE TABLE inventory_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inventory_num VARCHAR(255),
    inventable_id    BIGINT,
    inventable_type VARCHAR(255),
    CONSTRAINT pk_inventory_items PRIMARY KEY (id)
);

CREATE TABLE inventory_items_aud
(
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    id            BIGINT  NOT NULL,
    inventory_num VARCHAR(255)
    CONSTRAINT pk_inventory_items_aud PRIMARY KEY (rev, id)
);

CREATE TABLE space_assets
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    space_id          BIGINT,
    type_id           BIGINT,
    inventory_item_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_space_assets PRIMARY KEY (id)
);

CREATE TABLE space_assets_aud
(
    rev               INTEGER NOT NULL,
    revtype           SMALLINT,
    id                BIGINT  NOT NULL,
    space_id          BIGINT,
    type_id           BIGINT,
    inventory_item_id BIGINT,
    CONSTRAINT pk_space_assets_aud PRIMARY KEY (rev, id)
);

ALTER TABLE equipments
    ADD inventory_item_id BIGINT;

ALTER TABLE equipments
    ADD type_id BIGINT;

ALTER TABLE equipments
    ALTER COLUMN inventory_item_id SET NOT NULL;

ALTER TABLE equipments_aud
    ADD inventory_item_id BIGINT;

ALTER TABLE equipments_aud
    ADD type_id BIGINT;

ALTER TABLE equipment_types
    ADD CONSTRAINT uc_equipment_types_name UNIQUE (name);

ALTER TABLE inventory_items
    ADD CONSTRAINT uc_inventory_items_inventorynum UNIQUE (inventory_num);

ALTER TABLE applicant_aud
    ADD CONSTRAINT FK_APPLICANT_AUD_ON_IDRE FOREIGN KEY (id, rev) REFERENCES app_users_aud (id, rev);

ALTER TABLE equipments_aud
    ADD CONSTRAINT FK_EQUIPMENTS_AUD_ON_IDRE FOREIGN KEY (id, rev) REFERENCES reservables_aud (id, rev);

ALTER TABLE equipments
    ADD CONSTRAINT FK_EQUIPMENTS_ON_INVENTORYITEM FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id);

ALTER TABLE equipments
    ADD CONSTRAINT FK_EQUIPMENTS_ON_TYPE FOREIGN KEY (type_id) REFERENCES equipment_types (id);

ALTER TABLE equipment_types_aud
    ADD CONSTRAINT FK_EQUIPMENT_TYPES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE inventory_items_aud
    ADD CONSTRAINT FK_INVENTORY_ITEMS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_PETITIONER FOREIGN KEY (petitioner_id) REFERENCES applicant (id);

ALTER TABLE spaces_aud
    ADD CONSTRAINT FK_SPACES_AUD_ON_IDRE FOREIGN KEY (id, rev, rev) REFERENCES reservables_aud (id, rev);

ALTER TABLE space_assets_aud
    ADD CONSTRAINT FK_SPACE_ASSETS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE space_assets
    ADD CONSTRAINT FK_SPACE_ASSETS_ON_INVENTORYITEM FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id);

ALTER TABLE space_assets
    ADD CONSTRAINT FK_SPACE_ASSETS_ON_SPACE FOREIGN KEY (space_id) REFERENCES spaces (id);

ALTER TABLE space_assets
    ADD CONSTRAINT FK_SPACE_ASSETS_ON_TYPE FOREIGN KEY (type_id) REFERENCES equipment_types (id);

ALTER TABLE equipments
    DROP COLUMN inventory_num;