

CREATE TABLE inventory_items
(
    inventory_num VARCHAR(255) NOT NULL ,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inventory_items PRIMARY KEY (inventory_num)
);

CREATE TABLE inventory_items_aud
(
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    inventory_num VARCHAR(255),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inventory_items_aud PRIMARY KEY (rev, inventory_num)
);

ALTER TABLE inventory_items_aud
    ADD CONSTRAINT FK_INVENTORY_ITEMS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

INSERT INTO inventory_items (inventory_num, deleted_at)
SELECT DISTINCT
    e.inventory_num,
    r.deleted_at  -- propaga el soft delete existente
FROM equipments e
         INNER JOIN reservables r ON r.id = e.id;



ALTER TABLE equipments
    ADD inventory_item_id VARCHAR(255);

ALTER TABLE equipments_aud
    ADD inventory_item_id VARCHAR(255);

UPDATE equipments e
SET inventory_item_id = e.inventory_num;

ALTER TABLE equipments
    ALTER COLUMN inventory_item_id SET NOT NULL;

CREATE TABLE space_assets
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    space_id          BIGINT,
    name              VARCHAR(200) NOT NULL,
    description       VARCHAR(400) NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    created_by        VARCHAR(255) NOT NULL,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    type_id           BIGINT,
    inventory_item_id VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_space_assets PRIMARY KEY (id)
);

CREATE TABLE space_assets_aud
(
    rev               INTEGER NOT NULL,
    revtype           SMALLINT,
    id                BIGINT  NOT NULL,
    space_id          BIGINT,
    name              VARCHAR(200),
    description       VARCHAR(400),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    type_id           BIGINT,
    inventory_item_id VARCHAR(255),
    CONSTRAINT pk_space_assets_aud PRIMARY KEY (rev, id)
);

ALTER TABLE inventory_items
    ADD CONSTRAINT uc_inventory_items_inventorynum UNIQUE (inventory_num);

ALTER TABLE equipments
    ADD CONSTRAINT FK_EQUIPMENTS_ON_INVENTORYITEM FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (inventory_num);

ALTER TABLE space_assets_aud
    ADD CONSTRAINT FK_SPACE_ASSETS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE space_assets
    ADD CONSTRAINT FK_SPACE_ASSETS_ON_INVENTORYITEM FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (inventory_num);

ALTER TABLE space_assets
    ADD CONSTRAINT FK_SPACE_ASSETS_ON_SPACE FOREIGN KEY (space_id) REFERENCES spaces (id);

ALTER TABLE space_assets
    ADD CONSTRAINT FK_SPACE_ASSETS_ON_TYPE FOREIGN KEY (type_id) REFERENCES equipment_types (id);

ALTER TABLE equipments
    DROP COLUMN inventory_num;