-- Add id column to push_tokens
ALTER TABLE push_tokens ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Update primary key and add unique constraint on token
ALTER TABLE push_tokens DROP CONSTRAINT pk_push_tokens CASCADE;
ALTER TABLE push_tokens ADD CONSTRAINT pk_push_tokens PRIMARY KEY (id);
ALTER TABLE push_tokens ADD CONSTRAINT uk_push_tokens_token UNIQUE (token);

-- Update join table notifications_sent_to_tokens
ALTER TABLE notifications_sent_to_tokens ADD COLUMN sent_to_tokens_id BIGINT;
UPDATE notifications_sent_to_tokens n SET sent_to_tokens_id = p.id FROM push_tokens p WHERE n.sent_to_tokens_token = p.token;
ALTER TABLE notifications_sent_to_tokens ALTER COLUMN sent_to_tokens_id SET NOT NULL;
ALTER TABLE notifications_sent_to_tokens DROP COLUMN sent_to_tokens_token;
ALTER TABLE notifications_sent_to_tokens ADD CONSTRAINT fk_notsentotok_on_push_token FOREIGN KEY (sent_to_tokens_id) REFERENCES push_tokens (id);

-- Add id column to push_tokens_aud
ALTER TABLE push_tokens_aud ADD COLUMN id BIGINT;

-- Link id in aud table (for existing tokens)
UPDATE push_tokens_aud a SET id = p.id FROM push_tokens p WHERE a.token = p.token;

-- For deleted tokens in audit table, assign a unique id.
DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN SELECT DISTINCT token FROM push_tokens_aud WHERE id IS NULL LOOP
        -- Using the identity sequence to ensure uniqueness
        UPDATE push_tokens_aud SET id = nextval('push_tokens_id_seq') WHERE token = rec.token AND id IS NULL;
    END LOOP;
END $$;

-- Drop primary key on push_tokens_aud and add new one
ALTER TABLE push_tokens_aud DROP CONSTRAINT pk_push_tokens_aud;
ALTER TABLE push_tokens_aud ADD CONSTRAINT pk_push_tokens_aud PRIMARY KEY (rev, id);

-- Finalize id column in aud table
ALTER TABLE push_tokens_aud ALTER COLUMN id SET NOT NULL;

-- Update join table audit: notifications_sent_to_tokens_aud
ALTER TABLE notifications_sent_to_tokens_aud ADD COLUMN sent_to_tokens_id BIGINT;
-- Populate from main table if possible, otherwise from push_tokens_aud
UPDATE notifications_sent_to_tokens_aud n SET sent_to_tokens_id = p.id FROM push_tokens p WHERE n.sent_to_tokens_token = p.token;
UPDATE notifications_sent_to_tokens_aud n SET sent_to_tokens_id = pa.id FROM push_tokens_aud pa WHERE n.sent_to_tokens_token = pa.token AND n.sent_to_tokens_id IS NULL;

-- Drop primary key and recreate it
ALTER TABLE notifications_sent_to_tokens_aud DROP CONSTRAINT pk_notifications_sent_to_tokens_aud;
ALTER TABLE notifications_sent_to_tokens_aud DROP COLUMN sent_to_tokens_token;
ALTER TABLE notifications_sent_to_tokens_aud ALTER COLUMN sent_to_tokens_id SET NOT NULL;
ALTER TABLE notifications_sent_to_tokens_aud ADD CONSTRAINT pk_notifications_sent_to_tokens_aud PRIMARY KEY (notifications_sent_id, rev, sent_to_tokens_id);

-- Envers expects audit columns to be nullable
ALTER TABLE push_tokens_aud ALTER COLUMN token DROP NOT NULL;