CREATE SEQUENCE IF NOT EXISTS custom_revision_entity_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE app_users
(
    deleted_at   BOOLEAN                                 NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    birth_date   date                                    NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    last_login   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE app_users_aud
(
    rev          INTEGER NOT NULL,
    revtype      SMALLINT,
    id           BIGINT  NOT NULL,
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    birth_date   date,
    password     VARCHAR(255),
    last_login   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_users_aud PRIMARY KEY (rev, id)
);

CREATE TABLE applicant
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_applicant PRIMARY KEY (id)
);

CREATE TABLE custom_revision_entity
(
    id          INTEGER NOT NULL,
    timestamp   BIGINT  NOT NULL,
    remote_host VARCHAR(255),
    remote_user VARCHAR(255),
    CONSTRAINT pk_customrevisionentity PRIMARY KEY (id)
);

CREATE TABLE institutional_staff
(
    id              BIGINT       NOT NULL,
    employee_number VARCHAR(255) NOT NULL,
    CONSTRAINT pk_institutionalstaff PRIMARY KEY (id)
);

CREATE TABLE student
(
    id                  BIGINT       NOT NULL,
    registration_number VARCHAR(255) NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE user_admins
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_user_admins PRIMARY KEY (id)
);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_email UNIQUE (email);

ALTER TABLE institutional_staff
    ADD CONSTRAINT uc_institutionalstaff_employeenumber UNIQUE (employee_number);

ALTER TABLE student
    ADD CONSTRAINT uc_student_registrationnumber UNIQUE (registration_number);

CREATE INDEX idx_0360ad0769f620bb404249512 ON app_users (phone_number);

CREATE INDEX idx_225b36b5fd01076f438ab9411 ON app_users (deleted_at);

CREATE INDEX idx_27629ccf2080eea417f75bd2b ON app_users (email);

CREATE INDEX idx_39c12c42cf2b13ee863d437cc ON student (registration_number);

CREATE INDEX idx_6db8c93dd4a6f68884765760d ON app_users (first_name, last_name);

CREATE INDEX idx_baf3863df029d8f5b3e21d08a ON institutional_staff (employee_number);

ALTER TABLE applicant
    ADD CONSTRAINT FK_APPLICANT_ON_ID FOREIGN KEY (id) REFERENCES app_users (id);

ALTER TABLE app_users_aud
    ADD CONSTRAINT FK_APP_USERS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE institutional_staff
    ADD CONSTRAINT FK_INSTITUTIONALSTAFF_ON_ID FOREIGN KEY (id) REFERENCES applicant (id);

ALTER TABLE student
    ADD CONSTRAINT FK_STUDENT_ON_ID FOREIGN KEY (id) REFERENCES applicant (id);

ALTER TABLE user_admins
    ADD CONSTRAINT FK_USER_ADMINS_ON_ID FOREIGN KEY (id) REFERENCES app_users (id);