CREATE TABLE availabilities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_from     date                                    NOT NULL,
    date_to       date,
    start_time    time WITHOUT TIME ZONE,
    end_time      time WITHOUT TIME ZONE,
    day_of_week   VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    reservable_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_availabilities PRIMARY KEY (id)
);

CREATE TABLE availability_exceptions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_from     date                                    NOT NULL,
    date_to       date,
    start_time    time WITHOUT TIME ZONE,
    end_time      time WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    reservable_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_availability_exceptions PRIMARY KEY (id)
);

CREATE TABLE buildings
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(45)                             NOT NULL,
    CONSTRAINT pk_buildings PRIMARY KEY (id)
);

CREATE TABLE equipments
(
    id        BIGINT  NOT NULL,
    inventory INTEGER NOT NULL,
    spaces_id BIGINT,
    CONSTRAINT pk_equipments PRIMARY KEY (id)
);

CREATE TABLE reservables
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status             VARCHAR(15)                             NOT NULL,
    description        VARCHAR(400)                            NOT NULL,
    students_available BOOLEAN                                 NOT NULL,
    buildings_id       BIGINT,
    deleted_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_reservables PRIMARY KEY (id)
);

CREATE TABLE space_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(45)                             NOT NULL,
    description VARCHAR(400)                            NOT NULL,
    CONSTRAINT pk_space_types PRIMARY KEY (id)
);

CREATE TABLE spaces
(
    id             BIGINT NOT NULL,
    space_types_id BIGINT NOT NULL,
    CONSTRAINT pk_spaces PRIMARY KEY (id)
);

ALTER TABLE availabilities
    ADD CONSTRAINT FK_AVAILABILITIES_ON_RESERVABLE FOREIGN KEY (reservable_id) REFERENCES reservables (id);

ALTER TABLE availability_exceptions
    ADD CONSTRAINT FK_AVAILABILITY_EXCEPTIONS_ON_RESERVABLE FOREIGN KEY (reservable_id) REFERENCES reservables (id);

ALTER TABLE equipments
    ADD CONSTRAINT FK_EQUIPMENTS_ON_ID FOREIGN KEY (id) REFERENCES reservables (id);

ALTER TABLE equipments
    ADD CONSTRAINT FK_EQUIPMENTS_ON_SPACES FOREIGN KEY (spaces_id) REFERENCES spaces (id);

ALTER TABLE reservables
    ADD CONSTRAINT FK_RESERVABLES_ON_BUILDINGS FOREIGN KEY (buildings_id) REFERENCES buildings (id);

ALTER TABLE spaces
    ADD CONSTRAINT FK_SPACES_ON_ID FOREIGN KEY (id) REFERENCES reservables (id);

ALTER TABLE spaces
    ADD CONSTRAINT FK_SPACES_ON_SPACE_TYPES FOREIGN KEY (space_types_id) REFERENCES space_types (id);