CREATE TABLE notes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment        VARCHAR(255),
    reservation_id BIGINT                                  NOT NULL,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notes PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                  VARCHAR(255),
    body                   VARCHAR(255),
    sent_at                TIMESTAMP WITHOUT TIME ZONE,
    related_reservation_id BIGINT,
    user_id                BIGINT                                  NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE push_tokens
(
    is_active    BOOLEAN      NOT NULL,
    token        VARCHAR(255) NOT NULL,
    device_id    VARCHAR(255),
    platform     SMALLINT     NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    last_used_at TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT       NOT NULL,
    CONSTRAINT pk_push_tokens PRIMARY KEY (token)
);

CREATE TABLE reservation_recurrence
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_of_week   VARCHAR(255)                            NOT NULL,
    reservable_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_reservation_recurrence PRIMARY KEY (id)
);

CREATE TABLE reservations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    applicant_id  BIGINT                                  NOT NULL,
    reservable_id BIGINT                                  NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    start_time    time WITHOUT TIME ZONE                  NOT NULL,
    end_time      time WITHOUT TIME ZONE                  NOT NULL,
    date_from     date                                    NOT NULL,
    date_to       date                                    NOT NULL,
    approved_at   TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

CREATE TABLE reservations_aud
(
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    id            BIGINT  NOT NULL,
    applicant_id  BIGINT,
    reservable_id BIGINT,
    status        VARCHAR(255),
    start_time    time WITHOUT TIME ZONE,
    end_time      time WITHOUT TIME ZONE,
    date_from     date,
    date_to       date,
    approved_at   TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    CONSTRAINT pk_reservations_aud PRIMARY KEY (rev, id)
);

ALTER TABLE app_users
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE app_users
    ADD created_by VARCHAR(255);

ALTER TABLE app_users
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE app_users_aud
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE app_users_aud
    ADD created_by VARCHAR(255);

ALTER TABLE reservables
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE reservables
    ADD created_by TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE reservables
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE app_users
    ALTER COLUMN created_by SET NOT NULL;

ALTER TABLE reservables
    ALTER COLUMN created_by SET NOT NULL;

CREATE INDEX idx_6264661be4ef1e002ad594491 ON reservations (status);

CREATE INDEX idx_7724a794e2a563311ecdcd83b ON reservations (start_time, end_time);

CREATE INDEX idx_aa0ff773b5c8f6777605cdd0d ON reservations (date_from, date_to);

CREATE INDEX idx_decf1c1133ce79e7a342ca105 ON reservation_recurrence (day_of_week);

ALTER TABLE notes
    ADD CONSTRAINT FK_NOTES_ON_RESERVATION FOREIGN KEY (reservation_id) REFERENCES reservations (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_RELATEDRESERVATION FOREIGN KEY (related_reservation_id) REFERENCES reservations (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE push_tokens
    ADD CONSTRAINT FK_PUSH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE reservations_aud
    ADD CONSTRAINT FK_RESERVATIONS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_APPLICANT FOREIGN KEY (applicant_id) REFERENCES applicant (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_RESERVABLE FOREIGN KEY (reservable_id) REFERENCES reservables (id);

ALTER TABLE reservation_recurrence
    ADD CONSTRAINT FK_RESERVATION_RECURRENCE_ON_RESERVABLE FOREIGN KEY (reservable_id) REFERENCES reservables (id);

ALTER TABLE reservables
    DROP COLUMN deleted_at;

ALTER TABLE reservables
    ADD deleted_at BOOLEAN NOT NULL;

ALTER TABLE reservables
    ALTER COLUMN deleted_at SET NOT NULL;