CREATE TABLE log_in_attempts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    timestamp  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ip_address VARCHAR(15)                             NOT NULL,
    success    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_log_in_attempts PRIMARY KEY (id)
);