ALTER TABLE availabilities
    DROP CONSTRAINT FK_AVAILABILITIES_ON_RESERVABLE;

CREATE TABLE availabilities_aud
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    id          BIGINT  NOT NULL,
    date_from   date,
    date_to     date,
    start_time  time WITHOUT TIME ZONE,
    end_time    time WITHOUT TIME ZONE,
    day_of_week VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    group_id    BIGINT,
    CONSTRAINT pk_availabilities_aud PRIMARY KEY (rev, id)
);

CREATE TABLE availability_exceptions_aud
(
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    id            BIGINT  NOT NULL,
    date_from     date,
    date_to       date,
    start_time    time WITHOUT TIME ZONE,
    end_time      time WITHOUT TIME ZONE,
    reason        VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    reservable_id BIGINT,
    CONSTRAINT pk_availability_exceptions_aud PRIMARY KEY (rev, id)
);

CREATE TABLE availability_groups
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservable_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_availability_groups PRIMARY KEY (id)
);

CREATE TABLE availability_groups_aud
(
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    id            BIGINT  NOT NULL,
    reservable_id BIGINT,
    CONSTRAINT pk_availability_groups_aud PRIMARY KEY (rev, id)
);

ALTER TABLE availabilities
    ADD group_id BIGINT;

ALTER TABLE availabilities
    ALTER COLUMN group_id SET NOT NULL;

ALTER TABLE availabilities_aud
    ADD CONSTRAINT FK_AVAILABILITIES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE availabilities
    ADD CONSTRAINT FK_AVAILABILITIES_ON_GROUP FOREIGN KEY (group_id) REFERENCES availability_groups (id);

ALTER TABLE availability_exceptions_aud
    ADD CONSTRAINT FK_AVAILABILITY_EXCEPTIONS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE availability_groups_aud
    ADD CONSTRAINT FK_AVAILABILITY_GROUPS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE availability_groups
    ADD CONSTRAINT FK_AVAILABILITY_GROUPS_ON_RESERVABLE FOREIGN KEY (reservable_id) REFERENCES reservables (id);

ALTER TABLE availabilities
    DROP COLUMN reservable_id;