CREATE TABLE password_recovery_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jti        VARCHAR(255)                            NOT NULL,
    platform   VARCHAR(255)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used       BOOLEAN                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_password_recovery_tokens PRIMARY KEY (id)
);

CREATE TABLE password_recovery_tokens_aud
(
    rev        INTEGER NOT NULL,
    revtype    SMALLINT,
    id         BIGINT  NOT NULL,
    jti        VARCHAR(255),
    platform   VARCHAR(255),
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    used       BOOLEAN,
    user_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_password_recovery_tokens_aud PRIMARY KEY (rev, id)
);

ALTER TABLE password_recovery_tokens
    ADD CONSTRAINT uc_password_recovery_tokens_jti UNIQUE (jti);

ALTER TABLE password_recovery_tokens_aud
    ADD CONSTRAINT FK_PASSWORD_RECOVERY_TOKENS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE password_recovery_tokens
    ADD CONSTRAINT FK_PASSWORD_RECOVERY_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);