ALTER TABLE applicant_aud
    DROP CONSTRAINT fk_applicant_aud_on_idre;

ALTER TABLE equipments_aud
    DROP CONSTRAINT fk_equipments_aud_on_idre;

ALTER TABLE reservation_recurrence_aud
    DROP CONSTRAINT fk_reservation_recurrence_aud_on_rev;

ALTER TABLE reservation_recurrence
    DROP CONSTRAINT fk_reservation_recurrence_on_reservation;

ALTER TABLE reservations
    DROP CONSTRAINT fk_reservations_on_applicant;

ALTER TABLE spaces_aud
    DROP CONSTRAINT fk_spaces_aud_on_idre;

CREATE TABLE notification_preferences
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    type           VARCHAR(255)                            NOT NULL,
    email_enabled  BOOLEAN                                 NOT NULL,
    in_app_enabled BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_notification_preferences PRIMARY KEY (id)
);

CREATE TABLE notification_preferences_aud
(
    rev            INTEGER NOT NULL,
    revtype        SMALLINT,
    id             BIGINT  NOT NULL,
    user_id        BIGINT,
    type           VARCHAR(255),
    email_enabled  BOOLEAN,
    in_app_enabled BOOLEAN,
    CONSTRAINT pk_notification_preferences_aud PRIMARY KEY (rev, id)
);

CREATE TABLE notifications_sent_to_tokens
(
    notifications_sent_id BIGINT       NOT NULL,
    sent_to_tokens_token  VARCHAR(255) NOT NULL
);

CREATE TABLE notifications_sent_to_tokens_aud
(
    notifications_sent_id BIGINT       NOT NULL,
    rev                   INTEGER      NOT NULL,
    revtype               SMALLINT,
    sent_to_tokens_token  VARCHAR(255) NOT NULL,
    CONSTRAINT pk_notifications_sent_to_tokens_aud PRIMARY KEY (notifications_sent_id, rev, sent_to_tokens_token)
);

ALTER TABLE reservations
    ADD cancelled_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE reservations
    ADD companions INTEGER;

ALTER TABLE reservations
    ADD date date;

ALTER TABLE reservations
    ADD finished_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE reservations
    ADD petitioner_id BIGINT;

ALTER TABLE reservations
    ADD rejected_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE reservations
    ADD type SMALLINT;

ALTER TABLE reservations_aud
    ADD cancelled_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE reservations_aud
    ADD companions INTEGER;

ALTER TABLE reservations_aud
    ADD date date;

ALTER TABLE reservations_aud
    ADD finished_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE reservations_aud
    ADD petitioner_id BIGINT;

ALTER TABLE reservations_aud
    ADD rejected_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE reservations_aud
    ADD type SMALLINT;

ALTER TABLE notes
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE notes
    ADD created_by VARCHAR(255);

ALTER TABLE notes
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE notes
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE notes_aud
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE notes_aud
    ADD created_by VARCHAR(255);

ALTER TABLE notes_aud
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE notes
    ALTER COLUMN created_by SET NOT NULL;

ALTER TABLE reservations
    ALTER COLUMN date SET NOT NULL;

ALTER TABLE reservations
    ALTER COLUMN petitioner_id SET NOT NULL;

ALTER TABLE notifications
    ADD read_status VARCHAR(255);

ALTER TABLE notifications
    ADD type VARCHAR(255);

ALTER TABLE notifications
    ALTER COLUMN read_status SET NOT NULL;

ALTER TABLE notifications_aud
    ADD read_status VARCHAR(255);

ALTER TABLE notifications_aud
    ADD type VARCHAR(255);

ALTER TABLE notifications
    ALTER COLUMN type SET NOT NULL;

ALTER TABLE reservations
    ALTER COLUMN type SET NOT NULL;

ALTER TABLE notes
    ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE notification_preferences
    ADD CONSTRAINT uc_5a10515280eb7774cb0db4182 UNIQUE (user_id, type);

CREATE INDEX idx_225b36b5fd01076f438ab9411 ON app_users (deleted_at);

CREATE INDEX idx_9cefc745a085fdb9564f97e2a ON reservations (date, start_time, end_time);

CREATE INDEX idx_a4f8fe22a382daa6a028e7cca ON reservations (reservable_id);

ALTER TABLE applicant_aud
    ADD CONSTRAINT FK_APPLICANT_AUD_ON_IDRE FOREIGN KEY (id, rev) REFERENCES app_users_aud (id, rev);

ALTER TABLE equipments_aud
    ADD CONSTRAINT FK_EQUIPMENTS_AUD_ON_IDRE FOREIGN KEY (id, rev) REFERENCES reservables_aud (id, rev);

CREATE UNIQUE INDEX IX_pk_equipments_aud ON equipments_aud (id, rev);

ALTER TABLE notification_preferences_aud
    ADD CONSTRAINT FK_NOTIFICATION_PREFERENCES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE notification_preferences
    ADD CONSTRAINT FK_NOTIFICATION_PREFERENCES_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_PETITIONER FOREIGN KEY (petitioner_id) REFERENCES app_users (id);

ALTER TABLE spaces_aud
    ADD CONSTRAINT FK_SPACES_AUD_ON_IDRE FOREIGN KEY (id, rev) REFERENCES reservables_aud (id, rev);

CREATE UNIQUE INDEX IX_pk_spaces_aud ON spaces_aud (id, rev);

ALTER TABLE notifications_sent_to_tokens_aud
    ADD CONSTRAINT fk_notifications_sent_to_tokens_aud_on_rev FOREIGN KEY (rev) REFERENCES custom_revision_entity (id);

ALTER TABLE notifications_sent_to_tokens
    ADD CONSTRAINT fk_notsentotok_on_notification FOREIGN KEY (notifications_sent_id) REFERENCES notifications (id);

ALTER TABLE notifications_sent_to_tokens
    ADD CONSTRAINT fk_notsentotok_on_push_token FOREIGN KEY (sent_to_tokens_token) REFERENCES push_tokens (token);

DROP TABLE reservation_recurrence CASCADE;

DROP TABLE reservation_recurrence_aud CASCADE;

ALTER TABLE reservations
    DROP COLUMN applicant_id;

ALTER TABLE reservations
    DROP COLUMN date_from;

ALTER TABLE reservations
    DROP COLUMN date_to;

ALTER TABLE notes
    DROP COLUMN created_date;

ALTER TABLE spaces
    DROP COLUMN book_in_advance;

ALTER TABLE spaces
    ADD book_in_advance NUMERIC(21,0) NOT NULL default 86400000000000;

ALTER TABLE spaces_aud
    DROP COLUMN book_in_advance;

ALTER TABLE spaces_aud
    ADD book_in_advance NUMERIC(21,0);

ALTER TABLE availability_exceptions
    ALTER COLUMN date_to SET NOT NULL;

ALTER TABLE reservables
    ALTER COLUMN description DROP NOT NULL;

ALTER TABLE availabilities
    ALTER COLUMN end_time SET NOT NULL;

ALTER TABLE availability_exceptions
    ALTER COLUMN end_time SET NOT NULL;

ALTER TABLE push_tokens
    DROP COLUMN platform;

ALTER TABLE push_tokens
    ADD platform VARCHAR(255) NOT NULL;

ALTER TABLE push_tokens_aud
    DROP COLUMN platform;

ALTER TABLE push_tokens_aud
    ADD platform VARCHAR(255);

ALTER TABLE availabilities
    ALTER COLUMN start_time SET NOT NULL;

ALTER TABLE availability_exceptions
    ALTER COLUMN start_time SET NOT NULL;

ALTER TABLE reservables
    ALTER COLUMN updated_at SET NOT NULL;