name: build and deploy spring-api

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21
          cache: gradle

      - name: run tests
        run: ./gradlew clean test

  deploy:
    needs: build
    if: github.event_name == 'push'   # ❗ solo push, no PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21

      - name: build image
        run: |
          TAG=${{ github.ref_name }}
          ./gradlew bootBuildImage --imageName=${{ secrets.DOCKER_HUB_USERNAME }}/siges-api:$TAG

      - name: login docker
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: push image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/siges-api:${{ github.ref_name }}
